# Generated by Django 2.2 on 2021-01-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210124_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chosen',
            field=models.ManyToManyField(blank=True, related_name='_book_chosen_+', to='webapp.Book'),
        ),
    ]
