# Generated by Django 2.2 on 2021-01-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_book_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chosen',
        ),
        migrations.AddField(
            model_name='book',
            name='is_favorites',
            field=models.ManyToManyField(blank=True, related_name='_book_is_favorites_+', to='webapp.Book'),
        ),
    ]
